# Generated by Django 4.2.10 on 2024-03-04 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Место')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('periodicity', models.CharField(blank=True, choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('every 2 days', 'Через каждые 2 дня'), ('every 3 days', 'Через каждые 3 дня')], default='daily', max_length=100, null=True, verbose_name='Периодичность')),
                ('pleasant_habit', models.BooleanField(default=False, verbose_name='Идентификатор приятной привычки')),
                ('award', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Вознаграждение')),
                ('execution_time', models.TimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('publicity', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='Приятная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'полезная / приятная привычка',
                'verbose_name_plural': 'полезные / приятные привычки',
            },
        ),
    ]
