# Generated by Django 4.2.10 on 2024-03-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_options_alter_habit_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='activity',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Действие'),
        ),
    ]
