# Generated by Django 4.2.10 on 2024-03-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='activity',
            field=models.CharField(max_length=1000, verbose_name='Действие'),
        ),
    ]
