# Generated by Django 4.2.10 on 2024-03-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='activity',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Действие'),
        ),
    ]
