# Generated by Django 4.2.10 on 2024-03-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Периодичность'),
        ),
    ]
