# Generated by Django 4.2.10 on 2024-03-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_habit_created_at_habit_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Активность'),
        ),
    ]
