# Generated by Django 4.2.10 on 2024-03-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_remove_habit_last_date_worked_habit_date_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='date_worked',
        ),
        migrations.AddField(
            model_name='habit',
            name='notification_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время следующего оповещения'),
        ),
    ]
