# Generated by Django 4.2.10 on 2024-03-07 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_alter_habit_telegram_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='is_active',
        ),
    ]
